### ISSUE TITLE
reordering categories

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#7]
I reorder categories, but when go to view, they are still out of order.
I want "chemicals and hazcom c" before "chemicals and hazcom bc"
look good here:
![image](https://user-images.githubusercontent.com/31249115/29577712-7aa65020-873a-11e7-8101-c8c0792ae776.png)
but not here:
![image](https://user-images.githubusercontent.com/31249115/29577727-84ffbb88-873a-11e7-9210-0dc4b965c91d.png)

**Comment by michaelbmorris** [comment]
Done

**Comment by LoriStarnes** [comment]
This is still not working. On the slides page the "bc" is showing before the "c"
![image](https://user-images.githubusercontent.com/31249115/29580737-0c707d64-8745-11e7-97cd-8f70a87d3163.png)
